USE [master]
GO

/****** Object:  Database [FlightBooking]    Script Date: 13-05-2022 10:31:08 ******/
CREATE DATABASE [FlightBooking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FlightBooking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FlightBooking.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FlightBooking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FlightBooking_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FlightBooking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FlightBooking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FlightBooking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FlightBooking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FlightBooking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FlightBooking] SET ARITHABORT OFF 
GO

ALTER DATABASE [FlightBooking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FlightBooking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FlightBooking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FlightBooking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FlightBooking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FlightBooking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FlightBooking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FlightBooking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FlightBooking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FlightBooking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FlightBooking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FlightBooking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FlightBooking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FlightBooking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FlightBooking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FlightBooking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FlightBooking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FlightBooking] SET RECOVERY FULL 
GO

ALTER DATABASE [FlightBooking] SET  MULTI_USER 
GO

ALTER DATABASE [FlightBooking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FlightBooking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FlightBooking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FlightBooking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FlightBooking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FlightBooking] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FlightBooking] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FlightBooking] SET  READ_WRITE 
GO


